### ISSUE TITLE
Problem with white-space in <pre>

### ISSUE THREAD

**Issue by kulakowka** [vcapretz/bull-board#16]
Hello!

Thank you very much for the work done.
Your UI looks great.
But I have a problem with CSS.

<img width="1552" alt="Screen Shot 2019-09-19 at 7 24 11 AM" src="https://user-images.githubusercontent.com/557190/65213395-ae99f200-daae-11e9-8269-99c05fb42c53.png">

This can probably be solved with:

```css
pre {
      white-space: pre-wrap;
}
```
